### ISSUE TITLE
"stats" file missing

### ISSUE THREAD

**Issue by alexvioni** [pc2752/Multi_Voice_Sing_Speak_Sing#4]
Well I try to run the code and I get this error:
`Unable to open file (unable to open file: name = './stats/stats.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)`
and I see that many files and folders' content (which is required to run the application) is missing. Could you please add them or describe some help in the readme file on how to produce them myself?
Thanks a lot

**Comment by pc2752** [comment]
Stats file has been added. Thanks for pointing this out.
